geolaborapp/react-bootstrap-utils

- demo/FormExamples.jsx
- src/forms/FormDropdown.jsx
- src/mixed/Dropdown.jsx
Antes dessa correção, caso a props `includeEmptyItem` do componente `<FormDropdown />` fosse `true`, uma div vazia era incluída nas opções do dropdown para representar o valor "null". Caso o dev passasse um template para `<FormDropdown />`, a div vazia era formatada junto com os demais itens, o que causava esse tipo de problema: 
Código: 
Obs 1/2: `includeEmptyItem` por default já é `true`
``` js
<FormGroupDropdown
name="itemProgramacaoCampanha"
label="Item de Programação"
options={getItensProgramacaoFiltrados}
placeholder="Selecione o item de programação..."
childClassName="flex-nowrap"
itemClassName="border-bottom no-active"
menuClassName="p-0 w-100"
template={(label) => (
<div className="my-2">
<strong>Tipo de Equipamento: </strong>
<span>{label.tipoEquipamento ?? '-'}</span>
<div> …
```
> feat: makes the use of "template" more flexible for Dropdown and FormDropdown

- demo/FormExamples.jsx
- src/forms/FormAutocomplete.jsx
Erro: quando o valor inicial é "não listado" nas opções `items`, o componente não exibe esse "valor inicial", mesmo quando a prop `allowUnlistedValue` está definida como `true`.
> fix: load of an unlisted value in the form autocomplete

- demo/FormExamples.jsx
- src/forms/FormAutocomplete.jsx
- src/forms/helpers/form-helpers.js
Erro: quando o valor selecionado de um form autocomplete é um objeto, o valor no formData inicialmente era definido corretamente (isto é, um objeto) e logo em seguida era redefinido para um label.
https://user-images.githubusercontent.com/79877143/153650030-660df2c9-dd7e-4c1a-afd5-40982cb14476.mp4
Justificativa da correção: quando o "value" não é um objeto, o valor de value e label é igual, por isso o código funcionava. O valor de searchValue sempre corresponde ao label.
> fix: fixes selected item in FormAutocomplete after useFormControl setValue and when values are objects

- src/forms/FormAutocomplete.jsx
- src/forms2/FormAutocomplete.jsx
bug: erro ocorria quando:
1 - as options de um formAutocomplete ainda não haviam sido carregadas (dependiam de resposta de requisição ao servidor);
2 - a configuração allowUnlistedValue era escolhida
3 - o valor no formData respectivo ao componente do formAutocomplete vem prrenchido
4 - o valor (value) é um objeto (isto é, caso em que usamos a configuração trackBy)
Explicação:
como ainda não tinha options, o valor selecionado encaixava nesse caso:
Como o valor era um objeto, o `label` passava a ser um objeto e esse objeto era repassado diretamente para o jsx, causando o erro:
> fix: fixes initial load of formAutocomplete that allow unlisted values

- src/forms/helpers/form-helpers.js
- src/forms2/helpers/form-helpers.js
Enquanto testava edição de amostra, me deparei com esse caso.
Ao preencher o campo de input numérico e depois limpá-lo, o valor salvo no formData era NaN.
> fix: fixes NaN values for FormInput

- demo/FormExamples.jsx
- src/forms/FormLabel.jsx
- src/forms2/FormInputMask.jsx
When "required" was a function, the label would not work as expected. Regardless of the "required" result, the "label" was always "required false" because it was not a boolean.
> fix: fixes FormLabel when required prop is a function

- demo/Form2Examples.jsx
- demo/FormExamples.jsx
- src/forms/FormAutocomplete.jsx
- src/forms2/FormAutocomplete.jsx
- src/forms2/helpers/useFormControl.jsx
Task: https://app.clickup.com/t/21fc86n
Existem dois tipos de validação nesse formulário: a validação nativa e a validação usando a estilização do bootstrap. A propriedade que define o estilo da validação é "customValidation". O problema ocorre apenas na validação nativa, devido ao "display: none" do input. 
P.S.: a correção foi realizada no Form e Form2. Esse PR não corrige o problema descrito em https://app.clickup.com/t/2j978jp .
Sem correção: 
https://user-images.githubusercontent.com/50001507/179245144-297ea871-fae1-4268-9dc3-c85c3716c916.mp4
Com correção:
https://user-images.githubusercontent.com/50001507/179245160-b8a8c1dc-ff31-436b-aa63-8f5a81484381.mp4
> fix: required form autocomplete using native form validation

- demo/TabsExamples.jsx
- src/tabs/StatefulTabs.jsx
A prop "onSelect" era definida no PropTypes do StatefulTabs, mas ela nunca estava sendo utilizada.
> fix: corrige prop onSelect do StatefulTabs

- demo/Form2Examples.jsx
- src/forms2/helpers/useFormEffect.jsx
Possibilita passar dependencias para o effect que lida com os eventos
---
Este PR foi motivado pelo bug descrito no card "[corrigir exibição dos graficos de procedimentos na pre visualização do tipo de ensaio](https://app.clickup.com/t/864dxy583)". O bug acontecia porque não era possivel alterar um "formEffect" registrado sem parar de renderizar o componente em que ele foi registrado.
antes
https://user-images.githubusercontent.com/68669058/219108860-a21d7a67-4fd6-448d-bb1e-ba0db18ed822.mp4
depois
https://user-images.githubusercontent.com/68669058/219108886-8f0efdd1-c6ac-4cd1-992b-d83b347e6ed8.mp4
---
Videos gravados com o seguinte teste
```javascript
function Teste() {
const [toggleName, setToggleName] = useState(true);
return (
<div className=" d-flex flex-column">
<div className=" …
```
> feat: melhora useFormEffect

- demo/DropdownExamples.jsx
- demo/Form2Examples.jsx
- demo/FormExamples.jsx
- src/forms/FormAutocomplete.jsx
- src/forms/FormDropdown.jsx
- src/forms2/FormAutocomplete.jsx
- src/forms2/FormDropdown.jsx
- src/mixed/Dropdown.jsx
Este PR tem a intenção de implementar novas props para permitir a criação de um input autocomplete com scroll infinito.
A intenção dessa prop é facilitar o acesso ao scroll dos itens de um Dropdown/FormAutocomplete. Sem ela, seria necessario usar um "useRef" com um "document.querySelector", e mais um "useState" para resetar a ref no autocomplete quando ele fica sem itens no Dropdown.
A intenção dessa prop é possibilitar a execução de logica customizada após confirmar a limpeza dos filtros no autocomplete. Essa prop seria util em um caso especifico do https://github.com/geolaborapp/geolabor/pull/5650, em que ao digitar um filtro e clicar fora do autocomplete, o filtro visivel some, mas continua sendo aplicado na listagem de itens.
> feat: Adiciona props para Dropdown e FormAutocomplete

- demo/DialogExamples.jsx
- src/dialog/ModalPortal.jsx
Quando um Dialog possui um titulo ""dinamico"", ao alterar o titulo, o modal some, mas o backdrop continua na tela.
O componente `Dialog` cria um `ModalPortal` com um `Modal`, o ""diferencial"" é que este modal não fica ""dentro"" do """"html/componente"""" onde o `Dialog` foi adicionado.
O `ModalPortal` usa a função [ReactDOM.createPortal](https://react.dev/reference/react-dom/createPortal#usage), que """teleporta""" o conteudo do `Modal` para uma `div` diretamente dentro do `body` do html
Pelo que entendi, o erro era que ao atualizar o titulo, o `container` era removido do html, deixando o backdrop sem fechar o modal. 
Minha solução foi ajustar o effect para considerar apenas o `title` no array de dependencias, e sempre criar um novo container, porque esse `container` sempre será …
> fix: Corrige titulo dinamico em Dialog

- demo/Form2Examples.jsx
- src/forms2/FormAutocomplete.jsx
- src/forms2/FormCheckbox.jsx
- src/forms2/FormDropdown.jsx
- src/forms2/FormInput.jsx
- src/forms2/FormInputMask.jsx
- src/forms2/FormRadio.jsx
- src/forms2/FormSelect.jsx
- src/forms2/FormSwitch.jsx
- src/forms2/FormTextarea.jsx
- src/forms2/helpers/useFormControl.jsx
- src/forms2/helpers/useFormHelper.jsx
Este PR corrige https://app.clickup.com/t/864dn2h7a . Quando a função setValue era usada, o formulário não estava sendo corretamente atualizado, por mais que o state do form estivesse com o valor correto.
O problema era causado por múltiplas declarações do useFormControl referenciando um mesmo form element. Cada vez que o  useFormControl era declarado, um novo state era criado. Usando o setValue na declaração 1 do useFormControl não afetará o state na declaração 2 do useFormControl do mesmo elemento.
https://legacy.reactjs.org/docs/hooks-custom.html
A solução foi passar o state para o próprio elemento do form ao invés de deixá-lo no hook useFormControl
> fix: fixes use of setValue in form2

- demo/FormExamples.jsx
- demo/demo.jsx
- src/forms/FormAutocompleteTag.jsx
- src/forms/index.js
O PR #52 criou um bug na ficha de ensaio/investigação do geolabor. O PR #54 deve corrigir o problema. Se ese pr for revisado, mesclado e entrar em uma nova versão antes do pr 54 ser mesclado, vamos precisar de um revert no pr 52
---
Este PR tem a intenção de implementar o `FormAutocompleteTag` e o `FormGroupAutocompleteTag`.
Este componente tem o comportamento de um `FormAutocomplete` porem permite a seleção de mais de uma opção/tag.
Pro enquanto a implementação é apenas no `Form` para agilizar a revisão/correção deste PR(e porque existem alguns problemas no Form2 que acho melhor resolver antes de implementar uma nova funcionalidade)
https://github.com/geolaborapp/react-bootstrap-utils/assets/68669058/aace953d-488b-4eec-aa98-10f93b25aefc
> feat: adiciona FormAutocompleteTag

- demo/Form2Examples.jsx
- src/forms2/FormInputMask.jsx
- src/forms2/helpers/useFormControl.jsx
- src/forms2/helpers/useFormHelper.jsx
Ajustes para corrigir um dos problemas descrito https://github.com/geolaborapp/geolabor/pull/5946
Quando a ficha começava desbloqueada, depois era bloqueada, as alterações na ficha não eram salvas. Isso porque, na lógica avaliarEnsaio/avaliarInvestigacao ainda estava falando que a entidade estava no modo "somenteLeitura".
Esse problema foi causada pelo fato do "setValue" do formControl não ser atualizado depois do registro inicial. A correção foi fazer com que esse setValue possa ser atualizado.
PS: não consegui pensar em uma forma excelente de traduzir esse comportamento da ficha no FormExample2.
> fix(form2): corrige atualização do setValue do formControl

- demo/FormExamples.jsx
- src/forms/FormAutocompleteTag.jsx
Este PR tem a intenção de possibilitar a alteração dos icones dos botões do FormGroupAutocompleteTag e do FormAutocompleteTag. Como o geolabor não usa o cdn do bootstrap-icons é necessario passar os icones na hora de chamar o componente.
> feat: Possibilita trocar icone dos botões do FormGroupAutocompleteTag e do FormAutocompleteTag

- demo/FormExamples.jsx
- demo/UncontrolledFormExamples.jsx
- src/forms/helpers/form-helpers.js
- src/uncontrolled-forms/helpers/form-helpers.js
card [[react-bootstrap-utils] Ao "clear" uma data, o valor no estado passa a ser "invalid date"](https://app.clickup.com/t/86a0ypq0b)
O bug acontecia nos dois forms
---
1. Preencha um input datetime-local.
2. Clique em limpar
> fix: corrige invalid date ao limpar input datetime-local

- src/uncontrolled-forms/helpers/useUncontrolledFormControl.jsx
- src/uncontrolled-forms/helpers/useUncontrolledFormHelper.jsx
O fato do transform passar a ser executado na inicialização estava causando comportamentos indesejados na ficha de ensaio (lab e campo).
Seguindo o modelo do Form ("Form1"), o transform não deveria ser executado na inicialização. Este PR faz esse ajuste
> fix: deixa de executar transform na inicialização do UncontrolledForm

- src/forms2/helpers/useFormControl.jsx
O problema estava acontecendo nas fichas do geolabor, em campos de numero e data, que usam o "FormInputMask/FormGroupInputMask", ao carregar o Form2 com valores iniciais para esses campos, o valor estava preenchido no Form2 mas não era visivel.
Analisando mais a fundo, percebi que a alteração no PR https://github.com/geolaborapp/react-bootstrap-utils/pull/59 pode ter causado esse bug, porque o "afterSetValue" não estava sendo disparado na primeira renderização.
Vamos precisar gerar uma versão 0.26.47-2, porque as versões 0.26.48+ contem breaking changes(o Form2 foi renomeado para UncontrolledForm)
> fix: Corrige exibição do FormInputMask2 ao carregar valor inicial

- demo/FormExamples.jsx
- src/forms/FormAutocompleteTag.jsx
Durante a execução do card [Atualizar Filtros e implementar o autocomplete com scroll ininito como opção](https://app.clickup.com/t/86a0v3503), percebi alguns problemas com o FormAutocompleteTag e FormGroupAutocompleteTag:
- Passando um array de objetos para o "options", cada objeto deveria ter um "label", se não tivesse aconteceria um erro ""de react"" ao tentar exibir um objeto(no geolabor era uma tela do oops)
- O "allowUnlisted" values estava com um funcionamento estranho quando usado em conjunto com o "trackBy", ao adicionar um novo valor, era criado um objeto com "label" e "value", o correto seria usar o atributo no "trackBy" no lugar do "value"
> fix: corrige uso de label de tag e melhora uso do trackBy no FormAutocompleteTag

- demo/FormExamples.jsx
- src/forms/helpers/useForm.js
Este PR tem a intenção de corrigir um problema que acontece quando estamos usando `customValidations` no `Form` e o `validations` sofre uma alteração.
https://github.com/geolaborapp/react-bootstrap-utils/assets/68669058/2cd4d12b-8985-4b0f-8ad3-bf18cb9f11e4
https://github.com/geolaborapp/react-bootstrap-utils/assets/68669058/c0c98339-6a12-488b-9893-8161e52e5929
Percebi esse problema enquanto estava tentando alterar a validação do campo "coletaRealizadaPor" no form de edição de registro de campo de amostra do geolabor. A ideia era passar os colaboradores mobilizados carregados pelo redux na função de validação no "validations" do Form, para conseguir verificar se os colaboradores no Form estava mobilizados ou não sem usar o array de mobilizações, para padronizar com o que passou a ser feito …
> fix: corrige validação do form quando validations muda

- demo/FormExamples.jsx
- demo/UncontrolledFormExamples.jsx
- src/dialog/Dialog.jsx
- src/forms/FormInput.jsx
- src/uncontrolled-forms/UncontrolledFormInput.jsx
- src/uncontrolled-forms/UncontrolledFormInputMask.jsx
No https://github.com/geolaborapp/geolabor/pull/6724 foi percebido que para passar classes para inputs do RBU, era sempre necessario definir a classe "form-control" junto com as novas classes.
Acredito que ter que sempre reescrever uma classe não seja o ideal, então minha ideia foi fazer como é feito em outros componentes do RBU como o dropdown, e usar props para montar a classe no input.
UncontrolledFormGroupInputMask
UncontrolledFormGroupInput
FormGroupInput
> feat: facilita adicionar classes em FormInput, UncontrolledFormInput e UncontrolledFormInputMask

- demo/FormExamples.jsx
- src/forms/FormValidationFeedback.jsx
Este PR tornou-se necessário na implementação da customValidation dos campos de filtros do mapa de servicos-campo. A ideia é reproduzir o comportamento antigo (porém com o custom validation), em que a mensagem de erro de validação de 3 campos era exibida apenas em 1:
Para isso foi preciso que os campos Contrato e Campanha não tivessem mensagens de validação. No entanto o Form do rbu não permitia não passar a propriedade 'message', então o objetivo desse PR é passar a permitir a ausência dessa prop, exibindo uma string vazia quando não passada.
> feat: Permite não passar a propriedade message nas validations do Form

- demo/FormExamples.jsx
- demo/UncontrolledFormExamples.jsx
- src/forms/FormAutocomplete.jsx
- src/uncontrolled-forms/UncontrolledFormAutocomplete.jsx
Correção para um problema percebido no geolabor.
Quando usamos o autocomplete com o template, e o template usa o "value", o campo não estava mostrando o valor selecionado usando a formatação
Ex:
[Gravação de tela de 2025-04-01 14-11-37.webm](https://github.com/user-attachments/assets/f54a6134-d402-4a8a-8016-de7d2e83eeb6)
Depois da correção
[Gravação de tela de 2025-04-01 14-12-43.webm](https://github.com/user-attachments/assets/192c2b67-3556-4857-b52e-f7821e1ae8ac)
card https://app.clickup.com/t/86a6g41hd
> fix: corrige exibição de campos autocomplete usando o "value" no template
